import java.awt.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;


/*
 * mainJFrame.java
 *
 * Created on Jan 30, 2010, 1:03:30 AM
 */

/**
 *
 * @author mpiehl
 */

public class mainJFrame extends javax.swing.JFrame {
    /*Global Variable to hold program name*/
    public static String glob;
    /** Creates new form mainJFrame */
    public mainJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nidTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OTI Key Generator");

        jButton1.setText("Generate Key");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("NID:");

        jLabel2.setText("SSN:");

        ssnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addComponent(nidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        /*Gather our Text Field Options*/
        String nid = nidTextField.getText();
        String ssn = ssnTextField.getText();

        /*Generate program launch String*/
        String run = glob + " " + nid + " " + ssn;

        String[] cmd = {"/bin/bash","-c", run};

        try {
            /*Create a new process object bound to cmd*/
            ProcessBuilder process = new ProcessBuilder(cmd);

            /*Fork process to launch C binary*/
            Process p = process.start();

            /*Watch stdout stream*/
            InputStream is = p.getInputStream();
            InputStreamReader isr = new InputStreamReader(is);
            
            /*Watch stderr stream*/
            InputStream a = p.getErrorStream();
            InputStreamReader ab = new InputStreamReader(a);
            
            /*Gather Stream information*/
            BufferedReader ac = new BufferedReader(ab);
            BufferedReader br = new BufferedReader(isr);

            /*Strings to hold command line information*/
            String line, error;
            ArrayList<String> results = new ArrayList<String>();

       /*Debug printing program output to terminal*/
       while ((line = br.readLine()) != null)
       {
            results.add(line);
            System.out.println(line);
       }
       while ((error = ac.readLine()) != null) 
       {
            results.add(line);
            System.out.println(error);
       }

       /*Debugging*/
       //System.out.println("contents: " + results);

       /*Create our JFrame popup*/
       JFrame f = new JFrame("Generated Key");

       /*Set flowlayout to default*/
       Container content = f.getContentPane();
       content.setLayout(new FlowLayout());

       /*Make a Jlabel for each item in the arraylist*/
       JLabel[] labels = new JLabel[results.size()];

       /*Place each JLabel on the Frame*/
       for(int i = 0; i < labels.length; i++)
       {
            labels[i] = new JLabel((String)results.get(i));
            content.add(labels[i],BorderLayout.CENTER);
       }
       /*Set Screen Size and show the popup*/
       f.setSize(250,250);
       f.setVisible(true);

       }
       catch (IOException ex) {
            Logger.getLogger(mainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_jButton1ActionPerformed

    private void ssnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ssnTextFieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

      /*Set our global variable to program name*/
      glob = args[0];

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nidTextField;
    private javax.swing.JTextField ssnTextField;
    // End of variables declaration//GEN-END:variables

}
