#! /bin/bash

# **************************************************************************
# * Copyright (c) Enjellic Systems Development, LLC. All rights reserved.
# *
# * Please refer to the file named Documentation/COPYRIGHT in the top of
# * the source tree for copyright and licensing information.
# **************************************************************************/

#
# Wrapper script for execution of the idquery graphical identity
# generation client.
#

# Installation root.
# declare -r Root="/opt/Stgtgmgr";
declare Root=".";

# Certificate and password store.
# declare -r Certstore="$Root/lib/client/IDclient.jks";
declare -r Certstore="./IDclient.jks";
declare Certpassword;

# Java defines.
# declare Java_Defines="-cp $Root/lib/client/Stgtgclient.jar";
Java_Defines="$Java_Defines -Djavax.net.ssl.trustStore=$Certstore";
# -Djavax.net.debug=all used to requesting debug information.


# Read startup password and update defines to include keystore passwowrd.
# Default: hooter
# echo;
# read -r -s -p "Access password>" Certpassword;
Certpassword="hooter";
Java_Defines="$Java_Defines -Djavax.net.ssl.keyStorePassword=$Certpassword";


# Execute client.
java $Java_Defines idclient 2>&1 | tee debug.out;
