#! /bin/bash

# **************************************************************************
# * (C)Copyright IDfusion, LLC. All rights reserved.
# *
# * Please refer to the file named Documentation/COPYRIGHT in the top of
# * the source tree for copyright and licensing information.
# **************************************************************************/

#
# Wrapper script for execution of the AImanager graphical canister
# management tool.
#

# Installation root.
# declare -r Root="/opt/IDfusion";


# Java defines.
# declare Java_Defines="-cp $Root/lib//AImanager.jar";
# -Djavax.net.debug=all used to requesting debug information.


# Execute client.
java $Java_Defines AImanager 2>&1 | tee AImanager.log;
